client_id = "e2fe8af562188624a5119fa157e188f5"
name = "Team Banner Designer"
handle = "team-banner-designer"
application_url = "https://files-mentioned-by-the-user-shopify.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_files,write_files"

[auth]
redirect_urls = [
  "https://files-mentioned-by-the-user-shopify.vercel.app/auth/callback",
  "https://files-mentioned-by-the-user-shopify.vercel.app/auth/shopify/callback",
  "https://files-mentioned-by-the-user-shopify.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[app_proxy]
url = "https://files-mentioned-by-the-user-shopify.vercel.app/apps/team-banner-designer"
subpath = "team-banner-designer"
prefix = "apps"

[pos]
embedded = false
